version: '3'
services:
  openldap:
    # https://github.com/osixia/docker-openldap
    # https://www.openldap.org
    image: osixia/openldap:1.2.5
#    image: osixia/openldap:stable
    env_file: .env
    environment:
      LDAP_ORGANISATION: "IT Latinos NZ"
      LDAP_DOMAIN: "latintech.org"
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASS}
    ports:
      - 389:389
      - 636:636
#    https://github.com/osixia/docker-openldap?tab=readme-ov-file#seed-ldap-database-with-ldif
#    volumes:
#       - ./ldap:/container/service/slapd/assets/config/bootstrap/ldif/custom
#      - ./ldap:/var/lib/ldap
  ldap-client:
#   https://hub.docker.com/r/leenooks/phpldapadmin
    image: leenooks/phpldapadmin:2.0.0-dev
    depends_on:
      - openldap
    links:
      - "openldap:ldap"
    env_file: .env
    environment:
#      https://github.com/leenooks/phpLDAPadmin/wiki/Configuration-Variables
      APP_KEY: ${APP_KEY}
      LDAP_HOST: openldap
      LDAP_PORT: 389
      LDAP_USERNAME: cn=admin,dc=latintech,dc=org
      LDAP_PASSWORD: ${LDAP_ADMIN_PASS}
    ports:
      - "80:80"

  attendTrak:
    image: "aleon1220/attendance-webapp:${APP_WAR_FILE_VERSION}"
    env_file: .env
    ports:
      - "8080:8080"
#networks:
#  attend-trak-network: