version: '3'
services:
  openldap:
    # https://github.com/osixia/docker-openldap
    # https://www.openldap.org
    image: osixia/openldap:1.2.4
    env_file: .env
    environment:
      LDAP_ORGANISATION: "IT Latinos NZ"
      LDAP_DOMAIN: "latintech.org"
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASS}
    ports:
      - 389:389
      - 636:636
    # volumes:
    #   - ./ldap:/var/lib/ldap
    #   - ./ldap:/etc/ldap/slapd.d
  webapp:
    image: aleon1220/soa:latest
    env_file: .env
    ports:
      - 8080:8080
